/*Uarts*/
#define NVS_UART2_EN "UART2_EN"

/*Device*/
#define NVS_DEVICE_ID "DEVICE_ID"

/*Networks*/
#define NVS_WIFI_MODE "WIFI_MODE"

/*Wifi Ap*/
#define NVS_AP_SSID "AP_SSID"
#define NVS_AP_PASSWORD "AP_PASSWORD"
#define NVS_AP_AUTH_MODE "AP_AUTH_MODE"
#define NVS_AP_IP_ADDRESS "AP_IP_ADDRESS"
#define NVS_AP_SUBNET "AP_SUBNET"
#define NVS_AP_GATEWAY "AP_GATEWAY"
#define NVS_AP_MAC "AP_MAC"
#define NVS_AP_DHCP_ENABLE "AP_DHCP_ENLABLE"

/*Wifi Sta*/
#define NVS_STA_SSID "STA_SSID"
#define NVS_STA_PASSWORD "STA_PASSWORD"
#define NVS_STA_AUTH_MODE "STA_AUTH_MODE"
#define NVS_STA_IP_ADDRESS "STA_IP_ADDRESS"
#define NVS_STA_SUBNET "STA_SUBNET"
#define NVS_STA_GATEWAY "STA_GATEWAY"
#define NVS_STA_MAC "STA_MAC"
#define NVS_STA_TARGET_MAC "STA_TARGET_MAC"
#define NVS_STA_DHCP_ENABLE "STA_DHCP_ENABLE"

#define NVS_STA_API_HOST "STA_API_HOST"

/*Eth*/